## Sample YAML file for thermal-only processing. Irrelevant lines have been commented out.

PREPROCESSING:
  # RGB:
  #   CROP: True # for wide-angle TODO: True
  #   SCALE: 5
  THERMAL:
    H20T:
      FUNCTION: extract # or 'measure'
      DJI_THERMAL_SDK_PATH:  
    NORMALIZE: True 

DIR: # Note: for None, leave as blanks
  PROJECT: '2022_08_30_test'    
  H20T_DATA: 'auto'  # <single path to combined mapping_data folder(s) (i.e. for H20T)>, 'auto' becomes PROJECT/mapping_data
  RGB:               # <rgb_only dir -- can be wide-angle as our code crops> 
  THERMAL:           # <preprocessed thermal_only dir -- nothing else will be done by our code besides copying over>

# ------- IMPLEMENTED UP TO THIS LINE ----------- # 

STAGES:
  METHOD: thermal_only # or rgb_only or thermal_only - TODO: set all to True
  # COMBINED_STAGES:
  #   STAGE_1: False
  #   STAGE_2: False
  #   STAGE_3: False
  #   STAGE_4: False
  THERMAL:
    TWO_STEP: True # improves ortho performance
  DOWNSTREAM: True
  DOWNSTREAM_STAGES:
    TREE_DETECTION: True
    ATTACK_CLASSIFICATION: True

CAMERA: 'H20T' # 'H20T' or 'XT2' or 'other'

OUTPUT:
  DENORMALIZE: False
  OPTIMIZE_DISK_SPACE: False # TODO: implement



HOMOGRAPHY:
  MODE: NGF # 'NGF' or 'MANUAL' or 'UNALIGNED' (should be same as prefix of params)
  NGF_PARAMS:
    BATCH_SIZE: 64
    HIST_EQ: True
    LEVELS: 11
    DOWNSCALE: 1.5
    LEARNING_RATE: 0.5e-2
    N_ITERS: 400
    MI_LOWER_BOUND: 0.2
  MANUAL_PARAMS:
    IMAGE_PAIR_INDEX: 0


ODM:
  ## Uncomment options as needed
  # 3d-tiles: False
  # align: None
  # auto-boundary: False
  # auto-boundary-distance: 0 
  # bg-removal: False
  # boundary: ''
  build-overviews: ''
  # camera-lens: auto
  # cameras: ''
  # cog: False
  # copy-to: None
  # crop: 3
  # debug: 1
  # dem-decimation: 1
  # dem-euclidean-map: False
  # dem-gapfill-steps: 3
  # dem-resolution: 5
  # depthmap-resolution: 640
  # dsm: False
  # dtm: False
  # end-with: odm_postprocess
  # fast-orthophoto: False
  # feature-quality: high
  # feature-type: sift
  # force-gps: False
  # gcp: None
  # geo: None
  # gps-accuracy: 10
  # help: None
  ignore-gsd: ''
  matcher-neighbors: 16
  matcher-type: bruteforce
  # max-concurrency: 4
  # merge: all
  # mesh-octree-depth: 11
  # mesh-size: 200000
  min-num-features: 20000
  # name: code
  # no-gpu: False
  # optimize-disk-space: False # don't turn this to True for combined!
  # orthophoto-compression: DEFLATE
  # orthophoto-cutline: False
  # orthophoto-kmz: False
  # orthophoto-no-tiled: False
  # orthophoto-png: False
  orthophoto-resolution: 10.0
  # pc-classify: False
  # pc-copc: False
  # pc-csv: False
  # pc-ept: False
  # pc-filter: 2.5
  # pc-geometric: False
  # pc-las: False
  # pc-quality: medium
  # pc-rectify: False
  # pc-sample: 0
  # pc-tile: False
  # primary-band: auto
  # project-path: '' # TODO: check if this is needed
  # radiometric-calibration: none
  # rerun: ''
  rerun-all: ''
  # rerun-from: ''
  # resize-to: 2048
  # rolling-shutter: False
  # rolling-shutter-readout: 0
  # sfm-algorithm: incremental
  # skip-3dmodel: False
  # skip-band-alignment: False
  # skip-orthophoto: False
  # skip-report: False
  # sky-removal: False
  # sm-cluster: None
  # sm-no-align: False
  # smrf-scalar: 1.25
  # smrf-slope: 0.15
  # smrf-threshold: 0.5
  # smrf-window: 18.0
  # split: 999999
  # split-image-groups: None
  # split-overlap: 150
  # texturing-data-term: gmi
  # texturing-keep-unseen-faces: False
  # texturing-outlier-removal-type: gauss_clamping
  # texturing-skip-global-seam-leveling: False
  # texturing-skip-local-seam-leveling: False
  # texturing-tone-mapping: none
  # tiles: False
  time: ''
  # use-3dmesh: False
  use-exif: ''
  # use-fixed-camera-params: False
  # use-hybrid-bundle-adjustment: False
  # verbose: False
  # version: 






